name: bitchat_flutter_for_jp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.20.2

  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3

  # ★ CHANGE: 最新の安定バージョンに更新
  flutter_blue_plus: ^1.32.4

  permission_handler: ^11.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  riverpod_generator: ^2.4.0
  build_runner: ^2.4.10

flutter:
  uses-material-design: true
